user_user_homepage:
    path:     /
    defaults: { _controller: UserUserBundle:Default:index }

user_test_homepage:
    path:     /user
    defaults: { _controller: UserUserBundle:Default:showUser }

user_index:
    path:     /users
    defaults: { _controller: UserUserBundle:Default:role }

edit_user:
    path:     /user/edit/{id}
    defaults: { _controller: UserUserBundle:Default:edit }