gestion_note_homepage:
    path:     /
    defaults: { _controller: GestionNoteBundle:Default:index }

gestion_note:
    path:     /note
    defaults: { _controller: GestionNoteBundle:Default:listeNote }

ajouter_note:
    path:     /note/ajouter
    defaults: { _controller: GestionNoteBundle:Default:ajouterNote }

etudiant_list_ajax_call:
    path:     /ajax/etudiant_list
    defaults: { _controller: GestionNoteBundle:Default:ajaxGetEtudiant }
